# -*- coding: utf-8 -*-
"""proj03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0DsKjKhRCByUl4DV9qj2s4P_ebg94nJ

# Data Files
"""

import os
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy import stats
import matplotlib.pyplot as plt
from tqdm import tqdm
import time
from scipy.stats import t
import warnings
from statsmodels.tools.sm_exceptions import IterationLimitWarning

warnings.simplefilter("ignore", IterationLimitWarning)

baseline = pd.read_stata("2013-0533_data_baseline.dta")
census = pd.read_stata("2013-0533_data_census.dta")
endline1_2 = pd.read_stata("2013-0533_data_endlines1and2.dta")
endline1bustype = pd.read_stata("2013-0533_data_endline1businesstype.dta")

# from google.colab import drive
# drive.mount('/content/drive')

"""# Figures 2-5"""

from concurrent.futures import ProcessPoolExecutor
from scipy.stats import t

def one_boot(idx, rows, y, X, q):
    """Worker for one bootstrap draw – no pandas, only NumPy."""
    y_b  = y[rows]
    X_b  = X[rows, :]
    try:
        return sm.QuantReg(y_b, X_b).fit(q=q, max_iter=5000, p_tol=1e-6).params[1]
    except Exception:
        return np.nan # skipped draws return nan

def quantile_treatment_effect(df, outcome_var, treat_var='treat_dummy',
                                   cluster_var='areaid',
                                   quantiles=np.arange(0.05, 0.98, 0.02),
                                   n_bootstrap=100, ci=0.90,
                                   n_jobs=os.cpu_count()):
    start = time.time()

    sub_df = df[[outcome_var, treat_var, cluster_var]].dropna()
    y = sub_df[outcome_var].to_numpy()
    X = sm.add_constant(sub_df[treat_var]).to_numpy()
    clusters = sub_df[cluster_var].to_numpy()
    cluster_ids = np.unique(clusters)

    results = []
    np.random.seed(65209844)
    for q in tqdm(quantiles, "Progress"):
        # point estimate (quantile) and OLS
        q_model = sm.QuantReg(y, X).fit(q=q, max_iter=1000, p_tol=1e-6)
        q_est   = q_model.params[1]

        ols_est = sm.OLS(y, X).fit(
            cov_type='cluster', cov_kwds={'groups': clusters}
        ).params[1]

        boot_rows = []
        for _ in range(n_bootstrap):
            sampled_clusters = np.random.choice(cluster_ids, size=len(cluster_ids), replace=True)
            boot_rows.append(np.isin(clusters, sampled_clusters).nonzero()[0])


        # parallel bootstrap
        with ProcessPoolExecutor(max_workers=n_jobs) as pool:
            boot_coefs = list(pool.map(
                one_boot,
                range(n_bootstrap),
                boot_rows,
                [y]*n_bootstrap,
                [X]*n_bootstrap,
                [q]*n_bootstrap
            ))

        boot_coefs = np.asarray(boot_coefs, dtype=float)
        boot_coefs = boot_coefs[~np.isnan(boot_coefs)] # drop failed fits
        se  = boot_coefs.std(ddof=1)
        ts  = t.ppf(1-(1-ci)/2, df=len(boot_coefs)-1)
        ci_lower, ci_upper = q_est - ts*se, q_est + ts*se

        results.append((q, ols_est, q_est, ci_lower, ci_upper))

    time_taken = time.time() - start
    print(f"Finished {len(quantiles)} quantiles × {n_bootstrap} reps"
          f"  in {time_taken:.1f}s  [{n_jobs} cores]")

    out = pd.DataFrame(results, columns=['quantile','ols','qte','ci_lower','ci_upper'])
    out['percentile'] = (out['quantile']*100).astype(int)
    return out

# ==== Figure 2: Informal Borrowing ====
df = endline1_2
df['treat_dummy'] = (df['treatment'] == 'Treatment').astype(int)
fig2_df = quantile_treatment_effect(df, 'informal_amt_1')
plt.figure(figsize=(10, 6))
plt.plot(fig2_df['percentile'], fig2_df['qte'], color='gray', label='Quantile treatment effect')
plt.plot(fig2_df['percentile'], fig2_df['ols'], linestyle='--', color='black', label='OLS')
plt.plot(fig2_df['percentile'], fig2_df['ci_lower'], linestyle='-.', color='navy', label='90% C.I')
plt.plot(fig2_df['percentile'], fig2_df['ci_upper'], linestyle='-.', color='navy')
plt.title('Figure 2. Treatment Effect on Informal Borrowing\n(Endline 1)')
plt.xlabel('Percentile')
plt.ylabel('Treatment Effect')
plt.grid(True)
plt.xlim(0, 95)
plt.ylim(-25000, 20000)
plt.legend()
plt.tight_layout()
plt.savefig("figure2.pdf", bbox_inches='tight')
plt.show()

# ==== Figure 3: Business Profits - Old Businesses EL1 ====
df['bizprofit_1_old'] = df.loc[df['any_old_biz'] == 'Yes', 'bizprofit_1']
fig3_df = quantile_treatment_effect(df, 'bizprofit_1_old')
plt.figure(figsize=(10, 6))
plt.plot(fig3_df['percentile'], fig3_df['qte'], color='gray', label='Quantile treatment effect')
plt.plot(fig3_df['percentile'], fig3_df['ols'], linestyle='--', color='black', label='OLS')
plt.plot(fig3_df['percentile'], fig3_df['ci_lower'], linestyle='-.', color='navy', label='90% C.I')
plt.plot(fig3_df['percentile'], fig3_df['ci_upper'], linestyle='-.', color='navy')
plt.title('Figure 3. Treatment Effect on Business Profits\n(HHs who have an old business, Endline 1)')
plt.xlabel('Percentile')
plt.ylabel('Treatment Effect')
plt.grid(True)
plt.ylim(-5000, 10000)
plt.legend()
plt.tight_layout()
plt.savefig("figure3.pdf", bbox_inches='tight')
plt.show()

# ==== Figure 4: Business Profits - New Businesses EL1 ====
df['bizprofit_1_new'] = df.loc[(df['any_old_biz'] == 'No') & (df['any_biz_1'] == 1) &
                               (df['bizprofit_1'].between(-20000, 20000)), 'bizprofit_1']
fig4_df = quantile_treatment_effect(df, 'bizprofit_1_new')

# Get OLS on full untrimmed data
ols_df = df.loc[(df['any_old_biz'] == 'No') & (df['any_biz_1'] == 1)]
ols_y = ols_df['bizprofit_1']
ols_X = sm.add_constant(ols_df['treat_dummy'])
ols_model = sm.OLS(ols_y, ols_X, missing='drop').fit()
ols_value = ols_model.params['treat_dummy']

plt.figure(figsize=(9, 6))
plt.plot(fig4_df['percentile'], fig4_df['qte'], color='gray', label='Quantile treatment effect')
plt.axhline(y=ols_value, linestyle='--', color='black', label='OLS')
plt.plot(fig4_df['percentile'], fig4_df['ci_lower'], linestyle='-.', color='navy', label='90% C.I')
plt.plot(fig4_df['percentile'], fig4_df['ci_upper'], linestyle='-.', color='navy')
plt.title('Figure 4. Treatment Effect on Business Profits\n(HHs who have new business, Endline 1)')
plt.xlabel('Percentile')
plt.ylabel('Treatment Effect')
plt.grid(True)
plt.ylim(-12000, 12000)
plt.legend()
plt.tight_layout()
plt.savefig("figure4.pdf", bbox_inches='tight')
plt.show()

# ==== Figure 5: Business Profits - All Businesses EL2 ====
df['bizprofit_2_biz'] = df.loc[df['any_biz_2'] == 1, 'bizprofit_2']
fig5_df = quantile_treatment_effect(df, 'bizprofit_2_biz')
plt.figure(figsize=(10, 6))
plt.plot(fig5_df['percentile'], fig5_df['qte'], color='gray', label='Quantile treatment effect')
plt.plot(fig5_df['percentile'], fig5_df['ols'], linestyle='--', color='black', label='OLS')
plt.plot(fig5_df['percentile'], fig5_df['ci_lower'], linestyle='-.', color='navy', label='90% C.I')
plt.plot(fig5_df['percentile'], fig5_df['ci_upper'], linestyle='-.', color='navy')
plt.title('Figure 5. Treatment Effect on Business Profits\n(Full sample of business owners, Endline 2)')
plt.xlabel('Percentile')
plt.ylabel('Treatment Effect')
plt.grid(True)
plt.ylim(-2000, 6000)
plt.legend()
plt.tight_layout()
plt.savefig("figure5.pdf", bbox_inches='tight')
plt.show()

"""# Tables"""

# Define variable groups from the Stata locals
hh_composition = ["hh_size", "adults", "children", "male_head", "head_age", "head_noeduc"]
credit_access = ["spandana", "othermfi", "bank", "informal", "anyloan"]
loan_amt = ["spandana_amt", "othermfi_amt", "bank_amt", "informal_amt", "anyloan_amt"]
self_emp_activ = ["total_biz", "female_biz", "female_biz_pct"]
businesses = ["bizrev", "bizexpense", "bizinvestment", "bizemployees", "hours_weekbiz"]
businesses_allHH = ["bizrev_allHH", "bizexpense_allHH", "bizinvestment_allHH", "bizemployees_allHH", "hours_weekbiz_allHH"]
consumption = ["total_exp_mo", "nondurable_exp_mo", "durables_exp_mo", "home_durable_index"]

# Combine all into a single list
allvars = (
    hh_composition
    + credit_access
    + loan_amt
    + self_emp_activ
    + businesses
    + businesses_allHH
    + consumption
)

#############################################
################# Table 1A ##################
#############################################
# Create Summary Statistics Table
df1a = baseline.copy()
for var in businesses:
    df1a[f"{var}_allHH"] = df1a[var]
    df1a.loc[df1a["total_biz"] == 0, f"{var}_allHH"] = 0

#) Convert every “Yes”/“No” column to a numeric 0/1:
for col in ['spandana','othermfi','bank','informal','anyloan']:
    df1a[col] = df1a[col].map({'No': 0, 'Yes': 1})


results = []

for var in allvars:

    df = df1a[[var,'treatment','areaid']].copy()

    # ensure the encoded treatment dummy is only 0 and 1 for Treatment and Control
    df['treat_dummy'] = df['treatment'].map({'Treatment': 1, 'Control': 0})
    df = df.dropna(subset=[var, "treat_dummy", "areaid"])

    control = df[df['treat_dummy'] == 0].dropna()
    control[var] = control[var].astype('int64')
    N_ctrl    = control.shape[0]
    mean_ctrl = control[var].mean()
    sd_ctrl   = control[var].std(ddof=1)



    # b) cast numeric
    y = df[var].astype(float)

    X = sm.add_constant(df['treat_dummy'])
    ols = sm.OLS(y, X).fit()
    clust = ols.get_robustcov_results(
        cov_type='cluster',
        groups=df['areaid']
    )
    # d) pull out coefficient + p-value
    coef = clust.params[1]
    pval = clust.pvalues[1]

    results.append({
        "variable":     var,
        "Obs":          N_ctrl,
        "Control_mean": mean_ctrl,
        "Control_sd":   sd_ctrl,
        "Difference":   coef,
        "p_val":        pval
    })

table1a = pd.DataFrame(results).set_index("variable")
print()
print()
print("Table 1A: Baseline Summary Statistics")
print()
print(table1a)
print()
latex_df1a = table1a.to_latex(caption = None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df1a)

#############################################
################# Table 1B ##################
#############################################


df_orig = endline1_2
df      = df_orig.copy()

businesses = ["bizrev", "bizexpense", "bizinvestment", "bizemployees", "hours_week_biz"]
for i in [1, 2]:
    suf = f"_{i}"
    for var in businesses + ["female_biz"]:
        df[f"{var}_allHH{suf}"] = df[f"{var}{suf}"]
        mask = df[f"total_biz{suf}"] == 0
        df.loc[mask, f"{var}{suf}"] = np.nan

hh_composition    = ["hhsize", "adults", "children", "male_head", "head_age", "head_noeduc"]
credit_access     = ["spandana", "othermfi", "anybank", "anyinformal", "anyloan"]
loan_amt          = ["spandana_amt", "othermfi_amt", "bank_amt", "informal_amt", "anyloan_amt"]
self_emp_activ    = ["total_biz", "female_biz_allHH", "female_biz_pct"]
businesses_allHH  = [v + "_allHH" for v in businesses]
consumption       = ["total_exp_mo", "nondurable_exp_mo", "durables_exp_mo", "home_durable_index"]

allvars = (
    hh_composition
    + credit_access
    + loan_amt
    + self_emp_activ
    + businesses
    + businesses_allHH
    + consumption
)

# rename var_1 -> var1, var_2 -> var2
for var in allvars:
    df.rename(
        columns={f"{var}_1": f"{var}1", f"{var}_2": f"{var}2"},
        inplace=True
    )

df_long = pd.wide_to_long(
    df,
    stubnames=allvars,
    i=["hhid", "areaid", "treatment"],
    j="endline",
    sep="",
    suffix="\\d+"
).reset_index()

# dummy for endline==2
df_long["endline2"] = (df_long["endline"] == 2).astype(int)

# keep only what we need
df_long = df_long[["hhid", "areaid", "treatment", "endline", "endline2"] + allvars]

# Coerce any categorical analysis vars to numeric 0/1 codes
for var in allvars:
    if isinstance(df_long[var].dtype, pd.CategoricalDtype):
        df_long[var] = df_long[var].cat.codes.replace(-1, np.nan)
    else:
        df_long[var] = pd.to_numeric(df_long[var], errors="coerce")

# Calculate summary stats & cluster‐robust OLS for the Control group
results = []
control = df_long[df_long["treatment"] == "Control"]

for var in allvars:
    # Endline 1
    v1 = control.loc[control["endline"] == 1, var].dropna()
    N1, mean1, sd1 = v1.count(), v1.mean(), v1.std(ddof=1)
    # Endline 2
    v2 = control.loc[control["endline"] == 2, var].dropna()
    N2, mean2, sd2 = v2.count(), v2.mean(), v2.std(ddof=1)

    # Cluster‐robust regression of var on endline2
    regdf = control[["areaid", "endline2", var]].dropna(subset=[var])
    X = sm.add_constant(regdf["endline2"])
    y = regdf[var]
    m = sm.OLS(y, X).fit(
        cov_type="cluster",
        cov_kwds={"groups": regdf["areaid"]}
    )
    diff  = m.params["endline2"]
    p_val = m.pvalues["endline2"]

    results.append([N1, mean1, sd1, N2, mean2, sd2, diff, p_val])

table1b = pd.DataFrame(
    results,
    index=allvars,
    columns=[
        "Obs_el1", "Control_mean_el1", "Control_sd_el1",
        "Obs_el2", "Control_mean_el2", "Control_sd_el2",
        "Difference", "p_value"
    ]
)


table1b = table1b.round(2)

# display(table1b)
latex_df1b = table1b.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df1b)

#############################################
################# Table 2 ###################
#############################################

def addstars_table2(df):
    """
    Format the regression results from make_table() by adding stars and
    formatting coefficient (se) as a string column for Table 2 output.
    """
    def stars(p):
        return '***' if p < 0.01 else '**' if p < 0.05 else '*' if p < 0.10 else ''

    # Create a new column with formatted coef(se) and stars
    df = df.copy()
    df["coef(se)"] = df.apply(
        lambda row: f"{row['coef']:.3f}{stars(row['pval'])} ({row['se']:.3f})", axis=1
    )

    # Rearrange columns for display
    return df[["coef(se)", "mean_ctrl", "sd_ctrl", "N", "pval"]].round(2)



# list of controls used in the Stata $area_controls macro
area_controls = [
    "area_pop_base",
    "area_debt_total_base",
    "area_business_total_base",
    "area_exp_pc_mean_base",
    "area_literate_head_base",
    "area_literate_base",
]

# Panel A: Endline 1 variables & weight
vars_1 = [
    "spandana_1", "othermfi_1", "anymfi_1", "anybank_1", "anyinformal_1", "anyloan_1",
    "everlate_1", "mfi_loan_cycles_1",
    "spandana_amt_1", "othermfi_amt_1", "anymfi_amt_1", "bank_amt_1", "informal_amt_1",
    "anyloan_amt_1", "credit_index_1",
]
weight_1 = "w1"

# Panel B: Endline 2 variables & weight
vars_2 = [v.replace("_1", "_2") for v in vars_1]
weight_2 = "w2"

def make_table(df, var_list, weight_col):
    results = []
    for var in var_list:
        cols = [var, "treatment", weight_col, "areaid"] + area_controls
        regdf = df[cols].dropna().copy()

        for col in [var, "treatment"] + area_controls:
            if isinstance(regdf[col].dtype, pd.CategoricalDtype):
                regdf[col] = regdf[col].cat.codes.astype(float)
            else:
                regdf[col] = regdf[col].astype(float)
        regdf[weight_col] = regdf[weight_col].astype(float)

        # regression
        y = regdf[var]
        X = sm.add_constant(regdf[["treatment"] + area_controls])
        model = sm.WLS(y, X, weights=regdf[weight_col]) \
                  .fit(cov_type="cluster", cov_kwds={"groups": regdf["areaid"]})

        coef = model.params["treatment"]
        se   = model.bse  ["treatment"]
        df_r = model.df_resid
        pval = 2 * t.sf(abs(coef/se), df_r)

        # control‐group stats
        ctl = regdf.loc[regdf["treatment"] == 0, var]
        results.append({
            "variable":  var,
            "coef":      coef,
            "se":        se,
            "pval":      pval,
            "mean_ctrl": ctl.mean(),
            "sd_ctrl":   ctl.std(),
            "N":         len(regdf),
        })

    tab = pd.DataFrame(results).set_index("variable")
    return tab[["coef","se","mean_ctrl","sd_ctrl","N","pval"]].round(3)

# Call make_table() for endline 1 and endline 2
table2_endline1 = make_table(endline1_2, vars_1, "w1")
table2_endline2 = make_table(endline1_2, vars_2, "w2")

table2_endline1 = addstars_table2(table2_endline1)
table2_endline2 = addstars_table2(table2_endline2)

# display(table2_endline1)
# display(table2_endline2)
latex_df2_1 = table2_endline1.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)

print(latex_df2_1)
latex_df2_2 = table2_endline2.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)

print(latex_df2_2)

#############################################
################# Table 3 ###################
#############################################


t3df = endline1_2.copy()

vars3_1 = [
    "bizassets_1",
    "bizinvestment_1",
    "bizrev_1",
    "bizexpense_1",
    "bizprofit_1",
    "any_biz_1",
    "total_biz_1",
    "any_new_biz_1",
    "biz_stop_1",
    "newbiz_1",
    "female_biz_new_1",
    "biz_index_all_1",
]

vars3_2 = [v.replace("_1", "_2") for v in vars3_1]

# Build both panels using weight w1 (endline1) and w2 (endline2)
table3_endline1 = make_table(t3df, vars3_1, "w1")
table3_endline2 = make_table(t3df, vars3_2, "w2")

table3_endline1 = addstars_table2(table3_endline1)
table3_endline2 = addstars_table2(table3_endline2)

print("Table 3 — Panel A: Self-employment activities, Endline 1")
# display(table3_endline1)

print("\nTable 3 — Panel B: Self-employment activities, Endline 2")
# display(table3_endline2)

latex_df3_1 = table3_endline1.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df3_1)
latex_df3_2 = table3_endline2.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df3_2)

#############################################
################# Table 3B ##################
#############################################


df_old = endline1_2[endline1_2["any_old_biz"].cat.codes == 1]

# Variable lists for Panel A (wave 1) and Panel B (wave 2)
vars3b_1 = [
    "bizassets_1",
    "bizinvestment_1",
    "bizrev_1",
    "bizexpense_1",
    "bizprofit_1",
    "bizemployees_1",
    "biz_index_old_1",
]
vars3b_2 = [v.replace("_1", "_2") for v in vars3b_1]

table3b_endline1 = make_table(df_old, vars3b_1, "w1")
table3b_endline2 = make_table(df_old, vars3b_2, "w2")

table3b_endline1 = addstars_table2(table3b_endline1)
table3b_endline2 = addstars_table2(table3b_endline2)

print("Table 3B — Panel A: Old‐business households, Endline 1")
# display(table3b_endline1)

print("\nTable 3B — Panel B: Old‐business households, Endline 2")
# display(table3b_endline2)
latex_df3b_1 = table3b_endline1.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df3b_1)
latex_df3b_2 = table3b_endline2.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df3b_2)

#############################################
################# Table 3C ##################
#############################################


t3c_df = endline1_2.copy()

# Select the 7 outcomes and subset to newbiz_1>0 (non-missing)
vars3c = [
    "bizassets_1",
    "bizinvestment_1",
    "bizrev_1",
    "bizexpense_1",
    "bizprofit_1",
    "bizemployees_1",
    "biz_index_new_1",
]
df_new = t3c_df.loc[
    (t3c_df["newbiz_1"] > 0) & t3c_df["newbiz_1"].notna()
]

table3c = make_table(df_new, vars3c, "w1")
table3c = addstars_table2(table3c)
print("Table 3C — Households with new businesses, Endline 1")
# display(table3c)
latex_df3c = table3c.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df3c)

#############################################
################# Table 4 ##################
#############################################

df4 = endline1_2.copy()
df4["treat_dummy"] = (df4["treatment"] == "Treatment").astype(int)

# controls for baseline variables (Stata’s $area_controls)
area_controls = [
    "area_pop_base",
    "area_debt_total_base",
    "area_business_total_base",
    "area_exp_pc_mean_base",
    "area_literate_head_base",
    "area_literate_base"
]

# Endline 1 outcomes
panel_a = ["bizprofit_1", "wages_nonbiz_1", "income_index_1"]
results_a = []

for var in panel_a:
    regdf = df4[[var, "treat_dummy", "areaid", "w1"] + area_controls].dropna()
    y = regdf[var]
    X = sm.add_constant(regdf[["treat_dummy"] + area_controls])
    mod = sm.WLS(y, X, weights=regdf["w1"]).fit(
        cov_type="cluster", cov_kwds={"groups": regdf["areaid"]}
    )
    coef = mod.params["treat_dummy"]
    se   = mod.bse  ["treat_dummy"]
    pval = 2 * t.sf(abs(coef / se), df=mod.df_resid)

    ctrl = df4.loc[(df4["treat_dummy"] == 0) & df4[var].notna(), var]
    N    = ctrl.count()
    mean = ctrl.mean()
    sd   = ctrl.std(ddof=1)
    r2   = mod.rsquared

    results_a.append([N, mean, sd, coef, se, r2, pval])

table_a = pd.DataFrame(
    results_a,
    index=panel_a,
    columns=["Obs", "Ctl_mean", "Ctl_sd", "Coef", "SE", "R2", "p_value"]
).round(2)

# Endline 2 outcomes
panel_b = ["bizprofit_2", "wages_nonbiz_2", "income_index_2"]
results_b = []

for var in panel_b:
    regdf = df4[[var, "treat_dummy", "areaid", "w2"] + area_controls].dropna()
    y = regdf[var]
    X = sm.add_constant(regdf[["treat_dummy"] + area_controls])
    mod = sm.WLS(y, X, weights=regdf["w2"]).fit(
        cov_type="cluster", cov_kwds={"groups": regdf["areaid"]}
    )
    coef = mod.params["treat_dummy"]
    se   = mod.bse  ["treat_dummy"]
    pval = 2 * t.sf(abs(coef / se), df=mod.df_resid)

    ctrl = df4.loc[(df4["treat_dummy"] == 0) & df4[var].notna(), var]
    N    = ctrl.count()
    mean = ctrl.mean()
    sd   = ctrl.std(ddof=1)
    r2   = mod.rsquared

    results_b.append([N, mean, sd, coef, se, r2, pval])

table_b = pd.DataFrame(
    results_b,
    index=panel_b,
    columns=["Obs", "Ctl_mean", "Ctl_sd", "Coef", "SE", "R2", "p_value"]
).round(2)

table4 = pd.concat(
    [table_a, table_b],
    keys=["Endline 1", "Endline 2"]
)

# display(table4)
latex_df4 = table4.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df4)

#############################################
################# Table 5 ##################
#############################################

def addstars_table5(df):
    """
    Add stars and format Table 5-style regression output.

    Parameters:
    - df: DataFrame with columns ['Coef', 'SE', 'R2', 'Mean_ctl', 'SD_ctl', 'Obs', 'Pval']

    Returns:
    - Formatted DataFrame with 'coef(se)' column including significance stars
    """
    df = df.copy()

    def stars(p):
        return '***' if p < 0.01 else '**' if p < 0.05 else '*' if p < 0.10 else ''

    df["coef(se)"] = df.apply(
        lambda r: f"{r.Coef:.3f}{stars(r.Pval)} ({r.SE:.3f})", axis=1
    )

    return df[["coef(se)", "R2", "Mean_ctl", "SD_ctl", "Obs", "Pval"]].round(2)

df5 = endline1_2.copy()
df5["treat_dummy"] = (df5["treatment"] == "Treatment").astype(int)

area_controls = [
    "area_pop_base",
    "area_debt_total_base",
    "area_business_total_base",
    "area_exp_pc_mean_base",
    "area_literate_head_base",
    "area_literate_base"
]

def do_table(vars_list, weight_col):
    rows = []
    for var in vars_list:
        regdf = df5[[var, "treat_dummy", "areaid", weight_col] + area_controls].dropna()
        model = sm.WLS(
            regdf[var],
            sm.add_constant(regdf[["treat_dummy"] + area_controls]),
            weights=regdf[weight_col]
        ).fit(cov_type="cluster", cov_kwds={"groups": regdf["areaid"]})

        coef = model.params["treat_dummy"]
        se = model.bse["treat_dummy"]
        pval = 2 * t.sf(abs(coef/se), df=model.df_resid)

        ctrl = df5.loc[(df5["treat_dummy"] == 0) & df5[var].notna(), var]
        mn = ctrl.mean()
        sd = ctrl.std(ddof=1)
        N = regdf.shape[0]
        r2 = model.rsquared

        rows.append([coef, se, r2, mn, sd, N, pval])
    return pd.DataFrame(
        rows,
        index=vars_list,
        columns=["Coef", "SE", "R2", "Mean_ctl", "SD_ctl", "Obs", "Pval"]
    ).round(3)

vars_a = [
    "hours_week_1", "hours_week_biz_1", "hours_week_outside_1",
    "hours_girl1620_week_1", "hours_boy1620_week_1",
    "hours_headspouse_week_1", "hours_headspouse_biz_1", "hours_headspouse_outside_1",
    "labor_index_1"
]
table5_a = do_table(vars_a, weight_col="w1")

vars_b = [
    "hours_week_2", "hours_week_biz_2", "hours_week_outside_2",
    "hours_girl1620_week_2", "hours_boy1620_week_2",
    "hours_headspouse_week_2", "hours_headspouse_biz_2", "hours_headspouse_outside_2",
    "labor_index_2"
]
table5_b = do_table(vars_b, weight_col="w2")

table5 = pd.concat(
    [table5_a, table5_b],
    keys=["Panel A: Endline 1", "Panel B: Endline 2"]
)
table5 = addstars_table5(table5)
# display(table5)
latex_df5 = table5.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df5)

#############################################
################# Table 6 ##################
#############################################

# Stars Helper Function
def addstars_table6(df, mean_col, sd_col):
    """
    Take the DataFrame returned by weighted_regression()
    (with columns like 'coef_1', 'se_1', 'pval_1', …) and
    return a display-ready table that has one 'coef(se)' column
    with significance stars.
    """
    coef_col = next(c for c in df.columns if c.startswith("coef"))
    suff     = coef_col.replace("coef", "")        # ''  or  '_1' / '_2'

    tidy = df.rename(columns={
        f"coef{suff}": "coef",
        f"se{suff}"  : "se",
        f"pval{suff}": "pval",
        f"r2{suff}"  : "r2",
        f"N{suff}"   : "N"
    }).copy()

    def stars(p):
        return '***' if p < .01 else '**' if p < .05 else '*' if p < .10 else ''

    tidy["coef(se)"] = tidy.apply(
        lambda r: f"{r.coef:.3f}{stars(r.pval)} ({r.se:.3f})", axis=1
    )

    return tidy[["coef(se)", "r2", mean_col, sd_col, "N", "pval"]].round(2)

df6 = endline1_2.copy()
df6.head()

outcomes_1 = [
    "total_exp_mo_pc_1", "durables_exp_mo_pc_1", "nondurable_exp_mo_pc_1",
    "food_exp_mo_pc_1", "health_exp_mo_pc_1",
    "educ_exp_mo_pc_1", "temptation_exp_mo_pc_1", "festival_exp_mo_pc_1",
    "home_durable_index_1"
]

outcomes_2 = [
    "total_exp_mo_pc_2", "durables_exp_mo_pc_2", "nondurable_exp_mo_pc_2",
    "food_exp_mo_pc_2",  "health_exp_mo_pc_2",
    "educ_exp_mo_pc_2",  "temptation_exp_mo_pc_2", "festival_exp_mo_pc_2",
    "home_durable_index_2"
]

area_controls = [
    "area_pop_base", "area_debt_total_base", "area_business_total_base",
    "area_exp_pc_mean_base", "area_literate_head_base", "area_literate_base"
]

def weighted_regression(outcomes, weight_var, panel_tag, mn_label, sd_label):

  results6 = []
  for var in outcomes:
      cols = [var, "treatment", weight_var, "areaid"] + area_controls
      df = df6[cols].dropna().copy()

      y = df[var].astype(float)
      X = sm.add_constant(pd.concat([
                    (df["treatment"] == "Treatment").astype(int).rename("treatment"),
                    df[area_controls]
                ], axis=1))

      w = df[weight_var]

      wls = sm.WLS(y, X, weights=w).fit()
      clust = wls.get_robustcov_results(
          cov_type='cluster',
          groups=df['areaid']
      )

      beta  = clust.params[1]
      se    = clust.bse[1]
      tstat = beta / se
      pval  = 2 * stats.t.sf(abs(tstat), clust.df_resid)   # Stata ttail()

      ctrl  = df.loc[df["treatment"] == "Control", var]
      mn    = ctrl.mean()
      sd    = ctrl.std(ddof=1)

      results6.append({
          "variable": var,
          f"coef_{panel_tag}": beta,
          f"se_{panel_tag}":   se,
          f"pval_{panel_tag}": pval,
          mn_label:            mn,
          sd_label:            sd,
          f"r2_{panel_tag}":   clust.rsquared,
          f"N_{panel_tag}":    int(clust.nobs)
      })

  return pd.DataFrame(results6).set_index("variable")


table6_panelA = addstars_table6(
    weighted_regression(outcomes_1, "w1", "1", "mn1", "sd1"), "mn1", "sd1"
)
table6_panelB = addstars_table6(
    weighted_regression(outcomes_2, "w2", "2", "mn2", "sd2"), "mn2", "sd2"
)

# display(table6_panelA) # Table 6 – Panel A (Endline 1)
# display(table6_panelB) # Table 6 – Panel B (Endline 2)

latex_df6A = table6_panelA.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
latex_df6B = table6_panelB.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df6A)
print(latex_df6B)

#############################################
##############   Table 7  ###################
#############################################

df7 = endline1_2.copy() # same underlying data set

outcomes7_A = [
    "girl515_school_1", "boy515_school_1",
    "girl515_workhrs_pc_1", "boy515_workhrs_pc_1",
    "girl1620_school_1", "boy1620_school_1",
    "women_emp_index_1", "female_biz_new_1", "social_index_1"
]

outcomes7_B = [
    "girl515_school_2", "boy515_school_2",
    "girl515_workhrs_pc_2", "boy515_workhrs_pc_2",
    "girl1620_school_2", "boy1620_school_2",
    "women_emp_index_2", "female_biz_pct_2", "female_biz_new_2",
    "social_index_2"
]

area_controls = [
    "area_pop_base", "area_debt_total_base", "area_business_total_base",
    "area_exp_pc_mean_base", "area_literate_head_base", "area_literate_base"
]

table7_panelA = addstars_table6(
    weighted_regression(outcomes7_A, "w1", "1", "mn1", "sd1"),
    "mn1", "sd1"
)

table7_panelB = addstars_table6(
    weighted_regression(outcomes7_B, "w2", "2", "mn2", "sd2"),
    "mn2", "sd2"
)

# display(table7_panelA) # Table 7 – Panel A (Endline 1)
# display(table7_panelB) # Table 7 – Panel B (Endline 2)

latex_df7A = table7_panelA.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
latex_df7B = table7_panelB.to_latex(caption=None, label = None,
                 column_format= "lccccc", float_format = "%.2f", bold_rows = True,
                 escape = False)
print(latex_df7A)
print(latex_df7B)



